apiVersion: v1
kind: Service
metadata:
  name: slack
  namespace: dev
spec:
  selector:
    app: slack
  ports:
    - port: 8090
      targetPort: 8090
      name: slack
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: slack
  namespace: dev
spec:
  rules:
    - host: alert-slack.xd.com
      http:
        paths:
          - pathType: Prefix
            path: /api/v1/alert/
            backend:
              service:
                name: slack
                port:
                  number: 8090
  tls:
    - hosts:
        - alert-slack.xd.com
      secretName: xd
